CREATE TABLE `multipark_bookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`externalId` varchar(128) NOT NULL,
	`bookingNumber` varchar(64),
	`status` varchar(64),
	`checkIn` timestamp,
	`checkOut` timestamp,
	`checkInTime` varchar(8),
	`checkOutTime` varchar(8),
	`parkingType` varchar(32),
	`vehicleType` varchar(32),
	`clientFirstName` varchar(128),
	`clientLastName` varchar(128),
	`clientEmail` varchar(320),
	`clientPhone` varchar(64),
	`clientNif` varchar(32),
	`licensePlate` varchar(32),
	`vehicleBrand` varchar(64),
	`vehicleModel` varchar(64),
	`vehicleColor` varchar(32),
	`totalPrice` decimal(10,2),
	`currency` varchar(8) DEFAULT 'EUR',
	`arrivalFlight` varchar(32),
	`departureFlight` varchar(32),
	`notes` text,
	`rawJson` text,
	`syncedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `multipark_bookings_id` PRIMARY KEY(`id`),
	CONSTRAINT `multipark_bookings_externalId_unique` UNIQUE(`externalId`)
);
--> statement-breakpoint
CREATE TABLE `multipark_sync_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`syncType` varchar(64) NOT NULL,
	`status` varchar(32) NOT NULL,
	`recordsProcessed` int DEFAULT 0,
	`recordsCreated` int DEFAULT 0,
	`recordsUpdated` int DEFAULT 0,
	`errorMessage` text,
	`triggeredById` int,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `multipark_sync_logs_id` PRIMARY KEY(`id`)
);
